# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=20)),
                ('street_adress', models.CharField(max_length=100)),
                ('apt_nb', models.IntegerField(blank=True, null=True)),
                ('other', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['inflauser__infla_user__username', 'address_name'],
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unit', models.CharField(max_length=20)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
            options={
                'ordering': ['product__product_name'],
            },
        ),
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inflauser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflauser_birth', models.DateField(blank=True, null=True)),
                ('infla_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['infla_user__username'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_brand_or_variety', models.CharField(blank=True, max_length=50)),
                ('product_description', models.TextField(blank=True)),
                ('product_pic', models.ImageField(blank=True, upload_to=b'')),
            ],
            options={
                'ordering': ['product_name'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat1', models.CharField(blank=True, default=None, max_length=30)),
                ('subcategory1', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSubSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcat2', models.CharField(blank=True, default=None, max_length=30)),
                ('subcategory2', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=30)),
                ('store_location', models.CharField(default=None, max_length=30)),
                ('store_city', models.CharField(max_length=30)),
                ('store_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VE', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], max_length=30)),
                ('store_country', models.CharField(default='USA', max_length=30)),
                ('store_pic', models.ImageField(blank=True, upload_to=b'')),
                ('products', models.ManyToManyField(through='grocerystore.Availability', to='grocerystore.Product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_dietary',
            field=models.ManyToManyField(blank=True, to='grocerystore.Dietary'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcat1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcat2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubSubCategory'),
        ),
        migrations.AddField(
            model_name='availability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.Product'),
        ),
        migrations.AddField(
            model_name='availability',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.Store'),
        ),
        migrations.AddField(
            model_name='address',
            name='inflauser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.Inflauser'),
        ),
    ]
