# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-16 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocerystore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField()),
                ('purchase_amount', models.FloatField()),
                ('bought_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocerystore.Product')),
                ('bought_product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocerystore.ProductSubCategory')),
                ('purchase_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocerystore.Store')),
                ('purchaser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer__username', 'bought_product__product_name'],
            },
        ),
        migrations.RemoveField(
            model_name='productpurchasehistory',
            name='bought_product',
        ),
        migrations.RemoveField(
            model_name='productpurchasehistory',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productpurchasehistory',
            name='purchase_store',
        ),
        migrations.DeleteModel(
            name='ProductPurchaseHistory',
        ),
    ]
