# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 04:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubCategory'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductCategory', verbose_name='top product category'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='sub_category_name',
            field=models.CharField(max_length=30, verbose_name='product sub-category'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_address',
            field=models.CharField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_location',
            field=models.CharField(max_length=30, verbose_name='location name'),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip_city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='zipcode',
            name='zip_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.State'),
        ),
    ]
