# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-17 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0002_auto_20170615_2124'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['top_category'], 'verbose_name': 'Top category', 'verbose_name_plural': 'Top categories'},
        ),
        migrations.AlterModelOptions(
            name='productpurchase',
            options={'ordering': ['purchaser__username', 'bought_product__product_name']},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['parent__top_category', 'sub_category_name'], 'verbose_name': 'Product category', 'verbose_name_plural': 'Product categories'},
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='top_category',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductCategory', verbose_name='top category'),
        ),
        migrations.AlterField(
            model_name='productsubcategory',
            name='sub_category_name',
            field=models.CharField(max_length=30, verbose_name='sub-category'),
        ),
    ]
