# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-09 00:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0002_auto_20170108_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_location',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_name',
            field=models.CharField(max_length=30),
        ),
    ]
