# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 18:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0002_auto_20170111_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsubcategory',
            old_name='parent_category',
            new_name='top_category',
        ),
        migrations.RenameField(
            model_name='productsubsubcategory',
            old_name='parent_category',
            new_name='sub_category_1',
        ),
    ]
