# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 21:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0003_auto_20170512_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_data',
            new_name='data',
        ),
    ]
