# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 01:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocerystore', '0003_auto_20170108_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress_name', models.CharField(max_length=15)),
                ('street_adress', models.CharField(max_length=50)),
                ('apt_nb', models.IntegerField(blank=True)),
                ('other', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(max_length=30)),
                ('zip_code', models.IntegerField()),
                ('state', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_unit', models.CharField(max_length=20)),
                ('product_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('product_description', models.TextField(blank=True)),
                ('product_pic', models.ImageField(blank=True, upload_to=b'')),
                ('product_category', models.CharField(default=None, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Inflauser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inflauser_birth', models.DateField()),
                ('inflauser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('inflauser_address', models.ManyToManyField(to='grocerystore.Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_brand',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_pic',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_unit',
        ),
        migrations.AddField(
            model_name='product',
            name='product_brand_variety',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(blank=True, choices=[('OR', 'Organic'), ('HL', 'Halal'), ('KS', 'Kosher'), ('GF', 'Gluten-free'), ('GMO', 'Non-GMO'), ('VG', 'Veggie')], max_length=50),
        ),
        migrations.AddField(
            model_name='store',
            name='store_country',
            field=models.CharField(default='USA', max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='store_pic',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='store',
            name='store_state',
            field=models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VE', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('DC', 'District of Columbia')], default='USA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availability',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.Product'),
        ),
        migrations.AddField(
            model_name='availability',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.Store'),
        ),
        migrations.AddField(
            model_name='store',
            name='products',
            field=models.ManyToManyField(through='grocerystore.Availability', to='grocerystore.Product'),
        ),
    ]
