# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0003_auto_20170111_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubsubcategory',
            options={'ordering': ['parent_category', 'sub_category_1', 'sub_category_2']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcat1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcat2',
        ),
        migrations.AddField(
            model_name='productsubsubcategory',
            name='parent_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductCategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubSubCategory'),
        ),
    ]
