# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-13 00:18
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocerystore', '0004_auto_20170512_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_dates', django.contrib.postgres.fields.ArrayField(base_field=models.DateTimeField(), size=None)),
                ('nb_of_purchases', models.PositiveIntegerField(default=1)),
                ('bought_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocerystore.Product')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('purchase_store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='grocerystore.Store')),
            ],
            options={
                'ordering': ['customer__username', 'bought_product__product_name'],
            },
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='bought_product',
        ),
        migrations.RemoveField(
            model_name='producthistory',
            name='customer',
        ),
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
    ]
