# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 03:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0004_auto_20170109_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_brand_variety',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_type',
        ),
        migrations.AddField(
            model_name='availability',
            name='product_brand_variety',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='availability',
            name='product_type',
            field=models.CharField(blank=True, choices=[('OR', 'Organic'), ('HL', 'Halal'), ('KS', 'Kosher'), ('GF', 'Gluten-free'), ('GMO', 'Non-GMO'), ('VG', 'Veggie')], max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='apt_nb',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inflauser',
            name='inflauser_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
