# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0004_remove_product_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.CharField(max_length=15),
        ),
    ]
