# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0005_auto_20170512_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taxability',
            field=models.BooleanField(default=True),
        ),
    ]
