# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0005_auto_20170111_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productsubsubcategory',
            options={},
        ),
        migrations.AlterOrderWithRespectTo(
            name='productsubcategory',
            order_with_respect_to='top_category',
        ),
        migrations.AlterOrderWithRespectTo(
            name='productsubsubcategory',
            order_with_respect_to='parent_category',
        ),
    ]
