# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-15 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0005_auto_20161214_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_unit',
            field=models.CharField(max_length=20),
        ),
    ]
