# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0006_auto_20170109_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='availability',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='product_category',
        ),
        migrations.AddField(
            model_name='availability',
            name='product_dietary',
            field=models.ManyToManyField(blank=True, to='grocerystore.Dietary'),
        ),
        migrations.AddField(
            model_name='availability',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='grocerystore.ProductCategory'),
        ),
    ]
