# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0006_auto_20170111_1241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['inflauser__infla_user__username', 'address_name'], 'verbose_name_plural': 'addresses'},
        ),
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['product__product_name'], 'verbose_name_plural': 'availabilities'},
        ),
        migrations.AlterModelOptions(
            name='dietary',
            options={'ordering': ['name'], 'verbose_name_plural': 'dietaries'},
        ),
        migrations.AlterModelOptions(
            name='productsubcategory',
            options={'ordering': ['top_category', 'sub_category_1'], 'verbose_name': 'product sub-category', 'verbose_name_plural': 'product sub-categories'},
        ),
        migrations.AlterModelOptions(
            name='productsubsubcategory',
            options={'ordering': ['parent_category', 'sub_category_1', 'sub_category_2'], 'verbose_name': 'product sub-sub-category', 'verbose_name_plural': 'product sub-sub-categories'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='productsubcategory',
            order_with_respect_to=None,
        ),
        migrations.AlterOrderWithRespectTo(
            name='productsubsubcategory',
            order_with_respect_to=None,
        ),
    ]
