# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-14 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0006_product_taxability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['store__store_name', 'store__store_location', 'product__product_category__parent__top_category', 'product__product_category__sub_category_name', 'product__product_name'], 'verbose_name_plural': 'availabilities'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='zipcode',
            options={'ordering': ['zip_city', 'zipcode']},
        ),
        migrations.AlterField(
            model_name='itemincart',
            name='incart_quantity',
            field=models.FloatField(),
        ),
    ]
