# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0007_auto_20170111_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['top_category'], 'verbose_name_plural': 'product categories'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_category',
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcat1',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_subcat2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubSubCategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_topcat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductCategory'),
        ),
    ]
