# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0007_auto_20170109_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='dietary',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='availability',
            name='product_category',
            field=models.ManyToManyField(to='grocerystore.ProductCategory'),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductCategory'),
        ),
    ]
