# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 05:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0008_auto_20170109_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inflauser',
            options={'ordering': ['infla_user__username']},
        ),
        migrations.RenameField(
            model_name='address',
            old_name='adress_name',
            new_name='address_name',
        ),
        migrations.RenameField(
            model_name='inflauser',
            old_name='inflauser',
            new_name='infla_user',
        ),
    ]
