# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0008_auto_20170111_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_subcat1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_subcat2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='product_topcat',
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubSubCategory'),
        ),
    ]
