# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-10 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0009_auto_20170109_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='address',
            name='street_adress',
            field=models.CharField(max_length=100),
        ),
    ]
