# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-12 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0010_product_user_id_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubsubcategory',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='productsubsubcategory',
            name='sub_category_1',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='grocerystore.ProductSubCategory'),
        ),
        migrations.DeleteModel(
            name='ProductSubSubCategory',
        ),
    ]
