# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerystore', '0011_auto_20170111_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='product_store',
            field=models.ManyToManyField(through='grocerystore.Availability', to='grocerystore.Store'),
        ),
    ]
